import { defineConfig, globalIgnores } from 'eslint/config';
import nextVitals from 'eslint-config-next/core-web-vitals';
import nextTs from 'eslint-config-next/typescript';
import storybook from 'eslint-plugin-storybook';

// FSD layers, top to bottom. A layer may only import the layers below it.
const LAYERS = ['app', 'views', 'widgets', 'features', 'entities', 'shared'];

// All three forms are needed, or a bare `@/app` import slips past `@/app/*`.
const importsOf = (name) => [`@/${name}`, `@/${name}/*`, `@/${name}/**`];

const serverBan = {
  group: importsOf('server'),
  message: 'src/server доступен только из app/** — клиентский код ходит через REST-ручки.',
};

// Entity slices import each other only via @x. A `group` pattern can't express this exception.
const crossSliceBan = {
  regex: '^@/entities/(?![^/]+/@x/)',
  message: 'Кросс-импорт слайсов — только через @x: @/entities/<slice>/@x/<consumer>.',
};

function layerRules(layer, index) {
  const upperLayers = LAYERS.slice(0, index);
  const patterns = [serverBan];

  if (upperLayers.length > 0) {
    patterns.push({
      group: upperLayers.flatMap(importsOf),
      message: `Слой ${layer} не может импортировать слои выше себя: ${upperLayers.join(', ')}.`,
    });
  }
  if (layer === 'entities') patterns.push(crossSliceBan);

  return {
    files: [`src/${layer}/**`],
    rules: { 'no-restricted-imports': ['error', { patterns }] },
  };
}

export default defineConfig([
  ...nextVitals,
  ...nextTs,
  globalIgnores([
    '.next/**',
    'out/**',
    'build/**',
    'next-env.d.ts',
    'public/mockServiceWorker.js', // generated by `msw init`
    'storybook-static/**',
  ]),
  ...LAYERS.map(layerRules),
  ...storybook.configs['flat/recommended'],
]);
